export const countryCodes = [
  { code: "+93", name: "Afghanistan (AF)" },
  { code: "+355", name: "Albania (AL)" },
  { code: "+213", name: "Algeria (DZ)" },
  { code: "+376", name: "Andorra (AD)" },
  { code: "+244", name: "Angola (AO)" },
  { code: "+1-268", name: "Antigua and Barbuda (AG)" },
  { code: "+54", name: "Argentina (AR)" },
  { code: "+374", name: "Armenia (AM)" },
  { code: "+61", name: "Australia (AU)" },
  { code: "+43", name: "Austria (AT)" },
  { code: "+994", name: "Azerbaijan (AZ)" },
  { code: "+1-242", name: "Bahamas (BS)" },
  { code: "+973", name: "Bahrain (BH)" },
  { code: "+880", name: "Bangladesh (BD)" },
  { code: "+1-246", name: "Barbados (BB)" },
  { code: "+375", name: "Belarus (BY)" },
  { code: "+32", name: "Belgium (BE)" },
  { code: "+501", name: "Belize (BZ)" },
  { code: "+229", name: "Benin (BJ)" },
  { code: "+975", name: "Bhutan (BT)" },
  { code: "+591", name: "Bolivia (BO)" },
  { code: "+387", name: "Bosnia and Herzegovina (BA)" },
  { code: "+267", name: "Botswana (BW)" },
  { code: "+55", name: "Brazil (BR)" },
  { code: "+673", name: "Brunei (BN)" },
  { code: "+359", name: "Bulgaria (BG)" },
  { code: "+226", name: "Burkina Faso (BF)" },
  { code: "+257", name: "Burundi (BI)" },
  { code: "+855", name: "Cambodia (KH)" },
  { code: "+237", name: "Cameroon (CM)" },
  { code: "+1", name: "Canada / USA (CA/US)" },
  { code: "+238", name: "Cape Verde (CV)" },
  { code: "+236", name: "Central African Republic (CF)" },
  { code: "+235", name: "Chad (TD)" },
  { code: "+56", name: "Chile (CL)" },
  { code: "+86", name: "China (CN)" },
  { code: "+57", name: "Colombia (CO)" },
  { code: "+269", name: "Comoros (KM)" },
  { code: "+242", name: "Congo (CG)" },
  { code: "+243", name: "Congo, DR (CD)" },
  { code: "+506", name: "Costa Rica (CR)" },
  { code: "+225", name: "Cote d'Ivoire (CI)" },
  { code: "+385", name: "Croatia (HR)" },
  { code: "+53", name: "Cuba (CU)" },
  { code: "+357", name: "Cyprus (CY)" },
  { code: "+420", name: "Czech Republic (CZ)" },
  { code: "+45", name: "Denmark (DK)" },
  { code: "+253", name: "Djibouti (DJ)" },
  { code: "+1-767", name: "Dominica (DM)" },
  { code: "+1-809", name: "Dominican Republic (DO)" },
  { code: "+593", name: "Ecuador (EC)" },
  { code: "+20", name: "Egypt (EG)" },
  { code: "+503", name: "El Salvador (SV)" },
  { code: "+240", name: "Equatorial Guinea (GQ)" },
  { code: "+291", name: "Eritrea (ER)" },
  { code: "+372", name: "Estonia (EE)" },
  { code: "+268", name: "Eswatini (SZ)" },
  { code: "+251", name: "Ethiopia (ET)" },
  { code: "+679", name: "Fiji (FJ)" },
  { code: "+358", name: "Finland (FI)" },
  { code: "+33", name: "France (FR)" },
  { code: "+241", name: "Gabon (GA)" },
  { code: "+220", name: "Gambia (GM)" },
  { code: "+995", name: "Georgia (GE)" },
  { code: "+49", name: "Germany (DE)" },
  { code: "+233", name: "Ghana (GH)" },
  { code: "+30", name: "Greece (GR)" },
  { code: "+1-473", name: "Grenada (GD)" },
  { code: "+502", name: "Guatemala (GT)" },
  { code: "+224", name: "Guinea (GN)" },
  { code: "+245", name: "Guinea-Bissau (GW)" },
  { code: "+592", name: "Guyana (GY)" },
  { code: "+509", name: "Haiti (HT)" },
  { code: "+504", name: "Honduras (HN)" },
  { code: "+36", name: "Hungary (HU)" },
  { code: "+354", name: "Iceland (IS)" },
  { code: "+91", name: "India (IN)" },
  { code: "+62", name: "Indonesia (ID)" },
  { code: "+98", name: "Iran (IR)" },
  { code: "+964", name: "Iraq (IQ)" },
  { code: "+353", name: "Ireland (IE)" },
  { code: "+972", name: "Israel (IL)" },
  { code: "+39", name: "Italy (IT)" },
  { code: "+1-876", name: "Jamaica (JM)" },
  { code: "+81", name: "Japan (JP)" },
  { code: "+962", name: "Jordan (JO)" },
  { code: "+7", name: "Kazakhstan / Russia (KZ/RU)" },
  { code: "+254", name: "Kenya (KE)" },
  { code: "+686", name: "Kiribati (KI)" },
  { code: "+965", name: "Kuwait (KW)" },
  { code: "+996", name: "Kyrgyzstan (KG)" },
  { code: "+856", name: "Laos (LA)" },
  { code: "+371", name: "Latvia (LV)" },
  { code: "+961", name: "Lebanon (LB)" },
  { code: "+266", name: "Lesotho (LS)" },
  { code: "+231", name: "Liberia (LR)" },
  { code: "+218", name: "Libya (LY)" },
  { code: "+423", name: "Liechtenstein (LI)" },
  { code: "+370", name: "Lithuania (LT)" },
  { code: "+352", name: "Luxembourg (LU)" },
  { code: "+389", name: "North Macedonia (MK)" },
  { code: "+261", name: "Madagascar (MG)" },
  { code: "+265", name: "Malawi (MW)" },
  { code: "+60", name: "Malaysia (MY)" },
  { code: "+960", name: "Maldives (MV)" },
  { code: "+223", name: "Mali (ML)" },
  { code: "+356", name: "Malta (MT)" },
  { code: "+692", name: "Marshall Islands (MH)" },
  { code: "+222", name: "Mauritania (MR)" },
  { code: "+230", name: "Mauritius (MU)" },
  { code: "+52", name: "Mexico (MX)" },
  { code: "+691", name: "Micronesia (FM)" },
  { code: "+373", name: "Moldova (MD)" },
  { code: "+377", name: "Monaco (MC)" },
  { code: "+976", name: "Mongolia (MN)" },
  { code: "+382", name: "Montenegro (ME)" },
  { code: "+212", name: "Morocco (MA)" },
  { code: "+258", name: "Mozambique (MZ)" },
  { code: "+95", name: "Myanmar (MM)" },
  { code: "+264", name: "Namibia (NA)" },
  { code: "+674", name: "Nauru (NR)" },
  { code: "+977", name: "Nepal (NP)" },
  { code: "+31", name: "Netherlands (NL)" },
  { code: "+64", name: "New Zealand (NZ)" },
  { code: "+505", name: "Nicaragua (NI)" },
  { code: "+227", name: "Niger (NE)" },
  { code: "+234", name: "Nigeria (NG)" },
  { code: "+850", name: "North Korea (KP)" },
  { code: "+47", name: "Norway (NO)" },
  { code: "+968", name: "Oman (OM)" },
  { code: "+92", name: "Pakistan (PK)" },
  { code: "+680", name: "Palau (PW)" },
  { code: "+970", name: "Palestine (PS)" },
  { code: "+507", name: "Panama (PA)" },
  { code: "+675", name: "Papua New Guinea (PG)" },
  { code: "+595", name: "Paraguay (PY)" },
  { code: "+51", name: "Peru (PE)" },
  { code: "+63", name: "Philippines (PH)" },
  { code: "+48", name: "Poland (PL)" },
  { code: "+351", name: "Portugal (PT)" },
  { code: "+974", name: "Qatar (QA)" },
  { code: "+40", name: "Romania (RO)" },
  { code: "+250", name: "Rwanda (RW)" },
  { code: "+1-869", name: "Saint Kitts and Nevis (KN)" },
  { code: "+1-758", name: "Saint Lucia (LC)" },
  { code: "+1-784", name: "Saint Vincent (VC)" },
  { code: "+685", name: "Samoa (WS)" },
  { code: "+378", name: "San Marino (SM)" },
  { code: "+239", name: "Sao Tome and Principe (ST)" },
  { code: "+966", name: "Saudi Arabia (SA)" },
  { code: "+221", name: "Senegal (SN)" },
  { code: "+381", name: "Serbia (RS)" },
  { code: "+248", name: "Seychelles (SC)" },
  { code: "+232", name: "Sierra Leone (SL)" },
  { code: "+65", name: "Singapore (SG)" },
  { code: "+421", name: "Slovakia (SK)" },
  { code: "+386", name: "Slovenia (SI)" },
  { code: "+677", name: "Solomon Islands (SB)" },
  { code: "+252", name: "Somalia (SO)" },
  { code: "+27", name: "South Africa (ZA)" },
  { code: "+82", name: "South Korea (KR)" },
  { code: "+211", name: "South Sudan (SS)" },
  { code: "+34", name: "Spain (ES)" },
  { code: "+94", name: "Sri Lanka (LK)" },
  { code: "+249", name: "Sudan (SD)" },
  { code: "+597", name: "Suriname (SR)" },
  { code: "+46", name: "Sweden (SE)" },
  { code: "+41", name: "Switzerland (CH)" },
  { code: "+963", name: "Syria (SY)" },
  { code: "+886", name: "Taiwan (TW)" },
  { code: "+992", name: "Tajikistan (TJ)" },
  { code: "+255", name: "Tanzania (TZ)" },
  { code: "+66", name: "Thailand (TH)" },
  { code: "+228", name: "Togo (TG)" },
  { code: "+676", name: "Tonga (TO)" },
  { code: "+1-868", name: "Trinidad and Tobago (TT)" },
  { code: "+216", name: "Tunisia (TN)" },
  { code: "+90", name: "Turkey (TR)" },
  { code: "+993", name: "Turkmenistan (TM)" },
  { code: "+688", name: "Tuvalu (TV)" },
  { code: "+256", name: "Uganda (UG)" },
  { code: "+380", name: "Ukraine (UA)" },
  { code: "+971", name: "United Arab Emirates (AE)" },
  { code: "+44", name: "United Kingdom (GB)" },
  { code: "+598", name: "Uruguay (UY)" },
  { code: "+998", name: "Uzbekistan (UZ)" },
  { code: "+678", name: "Vanuatu (VU)" },
  { code: "+39", name: "Vatican City (VA)" },
  { code: "+58", name: "Venezuela (VE)" },
  { code: "+84", name: "Vietnam (VN)" },
  { code: "+967", name: "Yemen (YE)" },
  { code: "+260", name: "Zambia (ZM)" },
  { code: "+263", name: "Zimbabwe (ZW)" }
];
